name: oreon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons_flutter: ^3.1.6
  shared_preferences: ^2.5.4
  lucide_icons: ^0.257.0
  web_socket_channel: ^3.0.3
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.5+1
  sqflite: ^2.3.0 
  network_info_plus: ^7.0.0
  http: ^1.6.0
  image_picker: ^1.2.1
  crypto: ^3.0.3
  flutter_blue_plus: ^2.1.0
  permission_handler: ^12.0.1
  flutter_image_compress: ^2.4.0
  uuid : ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - ./assets/logo/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  linux: true
  image_path: "./assets/logo/logo.png"  # Ensure this is a 1024x1024 PNG
  adaptive_icon_background: "#ffffff"  # White background for Android adaptive icons
  adaptive_icon_foreground: "assets/oreon/res/mipmap-xxhdpi/oreon_adaptive_fore.png"  # Foreground (your logo, ideally with transparency)
  min_sdk_android: 21
  remove_alpha_ios: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/static/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/static/Roboto-ExtraLight.ttf
          weight: 200
        - asset: fonts/Roboto/static/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/static/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/static/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/static/Roboto-SemiBold.ttf
          weight: 600
        - asset: fonts/Roboto/static/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/static/Roboto-ExtraBold.ttf
          weight: 800
        - asset: fonts/Roboto/static/Roboto-Black.ttf
          weight: 900